### ISSUE TITLE
[RandomNoa] Replying to unknown message

### ISSUE THREAD

**Issue by JeffJrShim** [Noa-DiscordBot/Noa-Cogs#14]
### What cog is this bug report for?

RandomNoa

### Describe the bug

Currently, do take note that there's a bug, when the command invocation message is deleted, noa will have nowhere to reply to:
![image](https://user-images.githubusercontent.com/71493766/141449029-7a95bb4d-36d2-4e43-9807-fb9922a3349c.png)

To replicate, run the command, and delete the invocation message quickly before the bot catches up and processes your request.

### Please paste there error here, if any.

```python
Traceback (most recent call last):
  File "C:\Users\USER\noa\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\USER\Downloads\Noa Fukushima\data\cogs\CogManager\cogs\randomnoa\randomnoa.py", line 116, in randomnoa
    await ctx.reply(embed=embed, mention_author=False)
  File "C:\Users\USER\noa\lib\site-packages\discord\ext\commands\context.py", line 340, in reply
    return await self.message.reply(content, **kwargs)
  File "C:\Users\USER\noa\lib\site-packages\discord\message.py", line 1358, in reply
    return await self.channel.send(content, reference=self, **kwargs)
  File "C:\Users\USER\noa\lib\site-packages\discord\abc.py", line 1065, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "C:\Users\USER\noa\lib\site-packages\discord\http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In message_reference: Unknown message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\USER\noa\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\USER\noa\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\USER\noa\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In message_reference: Unknown message
```

**Comment by guacaplushy** [comment]
I think we just need a try/except block

**Comment by JeffJrShim** [comment]
Sorry, I still want the bot to respond even if the cmd is deleted

**Comment by JeffJrShim** [comment]
I'll fix this later

**Comment by guacaplushy** [comment]
> Sorry, I still want the bot to respond even if the cmd is deleted

reply with what?

**Comment by guacaplushy** [comment]
made it (hopefully) reply with the card
