### ISSUE TITLE
[RandomNoa] Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body In message_reference: Unknown message

### ISSUE THREAD

**Issue by JeffJrShim** [Noa-DiscordBot/Noa-Cogs#35]
### What cog is this bug report for?

RandomNoa

### Describe the bug

The issue is happening again after the recent rewrite. Refer to #14.

### Please paste there error here, if any.

```python
Traceback (most recent call last):
  File "C:\Users\USER\noa\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\USER\Downloads\Noa Fukushima\data\cogs\CogManager\cogs\randomnoa\randomnoa.py", line 43, in randomnoa
    await ctx.reply(embed=embed, mention_author=False)
  File "C:\Users\USER\noa\lib\site-packages\discord\ext\commands\context.py", line 340, in reply
    return await self.message.reply(content, **kwargs)
  File "C:\Users\USER\noa\lib\site-packages\discord\message.py", line 1358, in reply
    return await self.channel.send(content, reference=self, **kwargs)
  File "C:\Users\USER\noa\lib\site-packages\discord\abc.py", line 1065, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "C:\Users\USER\noa\lib\site-packages\discord\http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In message_reference: Unknown message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\USER\noa\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\USER\noa\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\USER\noa\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In message_reference: Unknown message
```

**Comment by JeffJrShim** [comment]
This will be fixed after my class in a bit.
