### ISSUE TITLE
[RandomNoa] KeyError

### ISSUE THREAD

**Issue by JeffJrShim** [Noa-DiscordBot/Noa-Cogs#40]
### What cog is this bug report for?

RandomNoa

### Describe the bug

[p]randomnoa, if we get a number generated which is 0, it will fail and break.

### Please paste there error here, if any.

```python
Traceback (most recent call last):
  File "C:\Users\USER\noa\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\USER\Downloads\Noa Fukushima\data\cogs\CogManager\cogs\randomnoa\randomnoa.py", line 36, in randomnoa
    data =  await self.random_noa()
  File "C:\Users\USER\Downloads\Noa Fukushima\data\cogs\CogManager\cogs\randomnoa\randomnoa.py", line 24, in random_noa
    "title": noas[random_index]["title"],
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\USER\noa\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\USER\noa\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\USER\noa\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 0
```

**Comment by JeffJrShim** [comment]
Closed in cd326fe
